### ISSUE TITLE
DateOnly cannot parse dates like "20160301"

### ISSUE THREAD

**Issue by colinking** [boblauer/dateonly#1]
You cannot create a DateOnly object by passing in the string-ified version of a DateOnly object ("20160301"). It does work if you parse it in as an integer.

Here is an example:
![image](https://cloud.githubusercontent.com/assets/2907397/14212432/d4555708-f800-11e5-96c5-81066cb3d21e.png)

**Comment by boblauer** [comment]
Thanks for the issue.  Not going to fix this though  - part of the goal is to maintain parity with the `Date` API, as much as possible at least:

``` js
> new Date(1459527260217)
'Fri Apr 01 2016 11:14:20 GMT-0500 (CDT)'
> new Date('1459527260217')
Invalid Date
```
