### ISSUE TITLE
Issue with date Conversion

### ISSUE THREAD

**Issue by unkn0wn-kgb** [boblauer/dateonly#2]
Hi there,

I think I discovered a serious issue with date conversion here is an example:

console.log(new DateOnly(20160101).toDate())
//Mon Feb 01 2016 00:00:00 GMT+1300 (NZDT) - Correct

Now we change year to 2017
console.log(new DateOnly(20170101).toDate())
//Wed Mar 01 2017 00:00:00 GMT+1300 (NZDT) - Not correct

So I'm not sure if you aware of this but if you could shine some light on why it works this way would be much appreciated.

Thanks

**Comment by boblauer** [comment]
Thanks, this is now fixed and published on npm `@1.1.1`.
