### ISSUE TITLE
Is there a way to store the month between 1 and 12?

### ISSUE THREAD

**Issue by sandrosimas** [boblauer/dateonly#4]
In the ````README.txt```` there is this information:
````
Returns the numeric representation of the DateOnly instance, of the form YYYYMMDD.
````
This library converts the month to a number between 0 and 11 which is not the correct representation of the format MM. I know that these formats are for strings and the dateonly library is working with numbers probably to create dates using the constructor (year, month, date) that receives months from 0 to 11.
I'm asking because I need to do some aggregations in MongDB and I'm using your other library mongoose-dateonly.
Here is my aggregation:
````
db.payment_orders.aggregate({
  $group: {
    _id: {
      $let: {
        vars: {
          date: {
            $dateFromString: {
              dateString: {$toString: "$payment_date"},
              format: "%Y%m%d"
            }
          }
        },
        in: {
          year: {$year: "$$date"},
          month: {$add: [{$month: "$$date"}, 1]},
        }
      }
    }
  }
});
````
I'm converting the dateonly number to string and then converting to date (wrongly because the month is incorrect). After that, I add 1 to the final month to get the correct month number.
Do you know what I can do to implement this aggregation in a better way, using dateonly as the field format?

**Comment by sandrosimas** [comment]
Do you think we can implement a second parameter called ````option```` in constructor?
Something like:
````
new DateOnly(..., {
  monthStartingWithZero: false
});

**Comment by boblauer** [comment]
Could you add 100 to the value in a projection before converting it to a date? That should bump the month part of the number up one.

**Comment by sandrosimas** [comment]
@boblauer, my code is working and I will try what you suggested but I don't know if its a good ideia, since this can result in wrong dates, for example: ````20180030 + 100 = 20180130````. 

````
console.log(20180030 + 100)
console.log(new Date(2018, 1, 30))
console.log(new DateOnly(20180030 + 100))
console.log(new DateOnly(20180030 + 100).toJSON())
````

````
20180130
2018-03-02T03:00:00.000Z
{ [Number: 20180202] date: 2, month: 2, year: 2018 }
20180202
````

**Comment by sandrosimas** [comment]
@boblauer, I could make it work this way, as you suggested to add 100 to the value before converting to a date:
````
aggregate.group({
    _id: {
      $let: {
        vars: {
          date: {
            $dateFromString: {
              dateString: {
                $toString: {
                  $toLong: {
                    $add: ['$payment_date', 100]
                  }
                }
              },
              format: '%Y%m%d',
            },
          },
        },
        in: {
          year: {$year: '$$date'},
          month: {$month: '$$date'},
        },
      },
    },
    amount: {$sum: '$amount'},
  });
````
